defaults: &defaults
  workingdrectory: ~/JP_Nodejs_project
  docker:
    - image: circleci/node:8
version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout:
      - run:
         - name: install npm
         - command: npm install
      - save_cache:
          key: v1-{{arch}}-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout:

      - restore_cache:
          key: v1-{{arch}}-cache-{{ checksum "package.json"}}
      - run:
          - name: set up test output
          - command: mkdir -p testresults/ava
      - run:
          - name: Run Test
          - command: npm test | npx tap-xunit > test-results/ava/results.xml

      - run:
          - name: Run cverage report
          - command: npm coverage > coverage-report.lcov
      - store_artifacts:
          path: test-results/ava/results.xml
          destination: test-resuts/ava/
      - store_artifacts:
          path: coverage-report.lcov
          destination: reports
      - store_test_results:
          path: test results
workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master









