
---
defaults:
  docker:
    -
      image: "circleci/node:8"
  workingdrectory: ~/JP_Nodejs_project
jobs:
  build:
    docker:
      -
        image: "circleci/node:8"
    steps:
      - checkout
      -
        run:
          -
            name: "npm install"
          -
            command: npm
      -
        save_cache:
          key: "v1-{{arch}}-cache-{{ checksum \"package.json\"}}"
          paths:
            - ./node_modules
    workingdrectory: ~/JP_Nodejs_project
  test:
    docker:
      -
        image: "circleci/node:8"
    steps:
      - checkout
      -
        restore_cache:
          key: "v1-{{arch}}-cache-{{ checksum \"package.json\"}}"
      -
        run:
          -
            name: "set up test output"
          -
            command: "mkdir -p testresults/ava"
      -
        run:
          -
            name: "Run Test"
          -
            command: "npm test | npx tap-xunit > test-results/ava/results.xml"
      -
        run:
          -
            name: "Run cverage report"
          -
            command: "yarn coverage > coverage-report.lcov"
      -
        store_artifacts:
          destination: test-resuts/ava/
          path: test-results/ava/results.xml
      -
        store_artifacts:
          destination: reports
          path: coverage-report.lcov
      -
        store_test_results:
          path: "test results"
    workingdrectory: ~/JP_Nodejs_project
version: |-
    2.1

    jobs - build - test requires - build filters branches only - master
workflow: ~

