


version: 2.1

parameters:
dependencies:


orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: cimg/node:17.3.0
    working_directory: ~/project
    steps:
      - checkout


      - run:

          name: npm install

          command: |
              npm install
              ls -al
              node --version
              echo "hello world"
  test:
    docker:
      - image: cimg/node:17.3.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: npm test
          command: |
            npm run test
            
          


workflow:
 version: 2.1
 build-test:
   jobs:
     - build:
     - test:
         requires:
           - build
         filters:
           branches:
             only: main











