


version: 2

parameters:
dependencies:


orbs:
  node: circleci/node@4.1.0
defaults: &defaults
  working_directory: ~/project
  docker:
    - image: cimg/node:17.3.0
jobs:
  build:
    docker:
      - image: cimg/node:17.3.0
    working_directory: ~/project
    steps:
      - checkout


      - run:

          name: npm install

          command: |
              npm install
              ls -al
              node --version
              echo "hello world"
      - save_cache:
          key: v1-{{arch}}-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{arch}}-cache-{{ checksum "package.json"}
      - run:
          name: set up test output directory
          command: | 
            mkdir -p test -p testresults/ava
      - run:
          name: Run tests
          command: |
           npm run test | npx tap-xunit > test-results/ava/results.xml
           






workflow:
 version: 2
 build-test:
   jobs:
     - build:
     - test:
         requires:
           - build
         filters:
           branches:
             only: main











