


version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: cimg/node:17.3.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: npm install
          command: |
              sudo yum install npm
              ls -al
              node --version
              echo "hello world" 

      - save_cache:
          key: v1-{{arch}}-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
  test:

    docker:
      - image: img/node:17.3.0




    steps:
      - checkout
      - run:
          name: install jest


      - restore_cache:
          key: v1-{{arch}}-cache-{{ checksum "package.json"}}
      - run:
            name: set up test output
            command: |
               mkdir -p testresults/ava
      - run:
          name: Run Test
          command: npm test | npx tap-xunit > test-results/ava/results.xml

      - run:
          name: Run cverage report
          command: npm coverage > coverage-report.lcov
      - store_artifacts:
          path: test-results/ava/results.xml
          destination: test-resuts/ava/
      - store_artifacts:
          path: coverage-report.lcov
          destination: reports
      - store_test_results:
          path: test results
workflow:
 version: 2.1
 build-test:
   jobs:
     - build:
     - test:
         requires:
           - build
         filters:
           branches:
             only: main













